FROM node:14.15.1-stretch-slim

# run in /app
WORKDIR /app

# copy source code to folder
COPY . .

RUN apt-get update

# install requirements
RUN apt-get -y install libtool automake autoconf nasm make

# install node requirements
RUN npm ci

# build prodiction static code in ./out
#RUN npm run production

# install an http server
RUN npm install --global http-server

# run basic webserver
# todo: make it run NGINX
CMD ["npm", "start"]
