FROM node:14.15.1-stretch-slim

RUN apt-get update

# install requirements
RUN apt-get -y install libtool automake autoconf nasm make git

# run in /app
WORKDIR /app

# copy source code to folder
COPY . .

# install node requirements
# RUN npm ci

# install an http server
RUN npm install --global http-server

# open port
EXPOSE 8080

# run basic webserver
# todo: make it run NGINX
RUN chmod +x docker-entrypoint.sh
#ENTRYPOINT ["docker-entrypoint.sh"]
ENTRYPOINT ["/bin/bash -c"]
CMD ["npm", "ci"]
CMD ["git", "clone https://github.com/Pips801/801labs-web"]
CMD ["cd", "./801labs-web/"]
CMD ["npm", "run production"]
CMD ["http-server", "out"]